export const POI_ENRICHMENT_CONCURRENCY = 1;
export const POI_ENRICHMENT_ATTEMPTS = 3;
export const POI_ENRICHMENT_BACKOFF_DELAY = 25000;
export const POI_ENRICHMENT_BACKOFF_TYPE = 'exponential';

export const POI_ENRICHMENT_JOB_NAME = 'enrichment-poi';

export const RETIAABLE_OVERPASS_ERROR = 'RETIAABLE_OVERPASS_ERROR';
export const UNRECOVERABLE_OVERPASS_ERROR = 'UNRECOVERABLE_OVERPASS_ERROR';
